all:
  children:
    servers:
      hosts:
        arq:
          ansible_host: 192.168.56.20
        db:
          ansible_host: 192.168.56.21
        app:
          ansible_host: 192.168.56.22
    clients:
      hosts:
        cli:
          ansible_host: 192.168.56.100
  vars:
    domain: "pedro.barbosa.devops"
    user1: "pedro"
    user2: "barbosa"
    users:
      - pedro
      - barbosa
    arq_ip: "192.168.56.20"
    db_ip: "192.168.56.21"
    app_ip: "192.168.56.22"
    db_mac: "08:00:27:AA:BB:01"
    app_mac: "08:00:27:AA:BB:02"
    ntp_server: "pool.ntp.br"
    timezone: "America/Recife"
    dhcp_network: "192.168.56.0"
    dhcp_netmask: "255.255.255.0"
    dhcp_range_start: "192.168.56.50"
    dhcp_range_end: "192.168.56.100"
    dhcp_router: "192.168.56.1"
